In [2]:
import pandas as pd
import numpy as np
import torch
from torch.utils.data import DataLoader, TensorDataset
import torch.nn as nn
import torch.optim as optim

In [3]:
df = pd.read_csv('train.csv')
print(df.shape)
df.head()

(891, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df = df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)
print(df.shape)
df.head()

(891, 8)

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [5]:
df = df.dropna()
print(df.shape)
df.head()

(712, 8)

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [6]:
max_age = df['Age'].max()
print(max_age)

df['Age'] = df['Age'] / max_age

df['Male'] = (df['Sex'] == 'male').astype(int)

df['Embarked_C'] = (df['Embarked'] == 'C').astype(int)
df['Embarked_S'] = (df['Embarked'] == 'S').astype(int)

df['Pclass1'] = (df['Pclass'] == 1).astype(int)
df['Pclass2'] = (df['Pclass'] == 2).astype(int)

df['Fare'] = np.log10(df['Fare'] + 1)

df['Ones'] = 1

df = df.drop(['Pclass', 'Sex', 'Embarked'], axis = 1)

print(df.shape)
df.head()

80.0
(712, 11)

,Survived,Age,SibSp,Parch,Fare,Male,Embarked_C,Embarked_S,Pclass1,Pclass2,Ones
0,0,0.2750,1,0,0.916454,1,0,1,0,0,1
1,1,0.4750,1,0,1.859038,0,1,0,1,0,1
2,1,0.3250,0,0,0.950608,0,0,1,0,0,1
3,1,0.4375,1,0,1.733197,0,0,1,1,0,1
4,0,0.4375,0,0,0.956649,1,0,1,0,0,1

In [7]:
X = df.iloc[:,1:].values
y = df.iloc[:, 0].values

In [ ]:
params = np.random.rand(10)
params